//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProgramlamaOdev.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebProgramlamaOdev.Resources.HomeTexts", typeof(HomeTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Adı.
        /// </summary>
        public static string E_C_KategoriAdi {
            get {
                return ResourceManager.GetString("E_C_KategoriAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string V_A_D_adres {
            get {
                return ResourceManager.GetString("V_A_D_adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat.
        /// </summary>
        public static string V_A_D_Fiyat {
            get {
                return ResourceManager.GetString("V_A_D_Fiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Detay Bilgileri.
        /// </summary>
        public static string V_A_D_h2Baslik {
            get {
                return ResourceManager.GetString("V_A_D_h2Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktar.
        /// </summary>
        public static string V_A_D_Miktar {
            get {
                return ResourceManager.GetString("V_A_D_Miktar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay Bekliyor.
        /// </summary>
        public static string V_A_D_OnayBekliyor {
            get {
                return ResourceManager.GetString("V_A_D_OnayBekliyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim.
        /// </summary>
        public static string V_A_D_Resim {
            get {
                return ResourceManager.GetString("V_A_D_Resim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Durumu.
        /// </summary>
        public static string V_A_D_SiparisDurumu {
            get {
                return ResourceManager.GetString("V_A_D_SiparisDurumu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Id.
        /// </summary>
        public static string V_A_D_SiparisId {
            get {
                return ResourceManager.GetString("V_A_D_SiparisId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Numarası.
        /// </summary>
        public static string V_A_D_SiparisNo {
            get {
                return ResourceManager.GetString("V_A_D_SiparisNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Tarihi.
        /// </summary>
        public static string V_A_D_SiparisTarihi {
            get {
                return ResourceManager.GetString("V_A_D_SiparisTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamamlandı.
        /// </summary>
        public static string V_A_D_Tamamlandi {
            get {
                return ResourceManager.GetString("V_A_D_Tamamlandi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam.
        /// </summary>
        public static string V_A_D_Toplam {
            get {
                return ResourceManager.GetString("V_A_D_Toplam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Adı.
        /// </summary>
        public static string V_A_D_UrunAdi {
            get {
                return ResourceManager.GetString("V_A_D_UrunAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Detay.
        /// </summary>
        public static string V_A_D_UrunDetay {
            get {
                return ResourceManager.GetString("V_A_D_UrunDetay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünler.
        /// </summary>
        public static string V_A_D_Urunler {
            get {
                return ResourceManager.GetString("V_A_D_Urunler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaylar.
        /// </summary>
        public static string V_A_I_Detaylar {
            get {
                return ResourceManager.GetString("V_A_I_Detaylar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Bilgileriniz.
        /// </summary>
        public static string V_A_I_h2Baslik {
            get {
                return ResourceManager.GetString("V_A_I_h2Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Numarası.
        /// </summary>
        public static string V_A_I_SiparisNo {
            get {
                return ResourceManager.GetString("V_A_I_SiparisNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Tarihi.
        /// </summary>
        public static string V_A_I_SiparisTarihi {
            get {
                return ResourceManager.GetString("V_A_I_SiparisTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutar.
        /// </summary>
        public static string V_A_I_Tutar {
            get {
                return ResourceManager.GetString("V_A_I_Tutar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string V_A_L_Giris {
            get {
                return ResourceManager.GetString("V_A_L_Giris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Girişi.
        /// </summary>
        public static string V_A_L_h2Baslik {
            get {
                return ResourceManager.GetString("V_A_L_h2Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Kullanıcı.
        /// </summary>
        public static string V_A_R_h2Baslik {
            get {
                return ResourceManager.GetString("V_A_R_h2Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Oluştur.
        /// </summary>
        public static string V_A_R_KullaniciOlustur {
            get {
                return ResourceManager.GetString("V_A_R_KullaniciOlustur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string V_C_C_Adres {
            get {
                return ResourceManager.GetString("V_C_C_Adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres Tanımı.
        /// </summary>
        public static string V_C_C_AdresTanimi {
            get {
                return ResourceManager.GetString("V_C_C_AdresTanimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Bilgileriniz.
        /// </summary>
        public static string V_C_C_h2Baslik {
            get {
                return ResourceManager.GetString("V_C_C_h2Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        public static string V_C_C_KullaniciAdi {
            get {
                return ResourceManager.GetString("V_C_C_KullaniciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahalle.
        /// </summary>
        public static string V_C_C_Mahalle {
            get {
                return ResourceManager.GetString("V_C_C_Mahalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen sipariş bilgilerinizi doldurunuz..
        /// </summary>
        public static string V_C_C_p {
            get {
                return ResourceManager.GetString("V_C_C_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posta Kodu.
        /// </summary>
        public static string V_C_C_PostaKodu {
            get {
                return ResourceManager.GetString("V_C_C_PostaKodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şehir.
        /// </summary>
        public static string V_C_C_Sehir {
            get {
                return ResourceManager.GetString("V_C_C_Sehir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semt.
        /// </summary>
        public static string V_C_C_Semt {
            get {
                return ResourceManager.GetString("V_C_C_Semt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siparişi Onayla.
        /// </summary>
        public static string V_C_C_SiparisiOnayla {
            get {
                return ResourceManager.GetString("V_C_C_SiparisiOnayla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alışveriş Devam Et.
        /// </summary>
        public static string V_C_Co_btnPrimary {
            get {
                return ResourceManager.GetString("V_C_Co_btnPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siparişiniz En Yakın Zamanda Kargoya Verilecek.
        /// </summary>
        public static string V_C_Co_h4Baslik {
            get {
                return ResourceManager.GetString("V_C_Co_h4Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Tamamlandı!.
        /// </summary>
        public static string V_C_Co_SiparisTamamlandi {
            get {
                return ResourceManager.GetString("V_C_Co_SiparisTamamlandi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alışverişe Devam Et.
        /// </summary>
        public static string V_C_I_DevamEt {
            get {
                return ResourceManager.GetString("V_C_I_DevamEt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat.
        /// </summary>
        public static string V_C_I_Fiyat {
            get {
                return ResourceManager.GetString("V_C_I_Fiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alışveriş Sepeti.
        /// </summary>
        public static string V_C_I_h2Baslik {
            get {
                return ResourceManager.GetString("V_C_I_h2Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktar.
        /// </summary>
        public static string V_C_I_Miktar {
            get {
                return ResourceManager.GetString("V_C_I_Miktar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string V_C_I_Sil {
            get {
                return ResourceManager.GetString("V_C_I_Sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alışverişi Tamamla.
        /// </summary>
        public static string V_C_I_Tamamla {
            get {
                return ResourceManager.GetString("V_C_I_Tamamla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam.
        /// </summary>
        public static string V_C_I_Toplam {
            get {
                return ResourceManager.GetString("V_C_I_Toplam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Adı.
        /// </summary>
        public static string V_C_I_UrunAdi {
            get {
                return ResourceManager.GetString("V_C_I_UrunAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alışveriş Sepetinizide Ürün Bulunmamaktadır..
        /// </summary>
        public static string V_C_I_UrunBulunmamakta {
            get {
                return ResourceManager.GetString("V_C_I_UrunBulunmamakta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string V_Cat_C_btnKaydet {
            get {
                return ResourceManager.GetString("V_Cat_C_btnKaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Kategori.
        /// </summary>
        public static string V_Cat_C_h2Baslik {
            get {
                return ResourceManager.GetString("V_Cat_C_h2Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kategoriyi silmek istediğinizden emin misiniz?.
        /// </summary>
        public static string V_Cat_Del_h2Baslik {
            get {
                return ResourceManager.GetString("V_Cat_Del_h2Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Listesine Geri Dön.
        /// </summary>
        public static string V_Cat_Del_KategoriDon {
            get {
                return ResourceManager.GetString("V_Cat_Del_KategoriDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string V_Cat_Del_Sil {
            get {
                return ResourceManager.GetString("V_Cat_Del_Sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        public static string V_Cat_Det_Duzenle {
            get {
                return ResourceManager.GetString("V_Cat_Det_Duzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaylar.
        /// </summary>
        public static string V_Cat_Det_h2Baslik {
            get {
                return ResourceManager.GetString("V_Cat_Det_h2Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        public static string V_Cat_Det_h4Baslik {
            get {
                return ResourceManager.GetString("V_Cat_Det_h4Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alışveriş Listesine Geri Dön.
        /// </summary>
        public static string V_Cat_Det_ListeyeDon {
            get {
                return ResourceManager.GetString("V_Cat_Det_ListeyeDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Güncelle.
        /// </summary>
        public static string V_Cat_E_h2Baslik {
            get {
                return ResourceManager.GetString("V_Cat_E_h2Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string V_Cat_E_Kaydet {
            get {
                return ResourceManager.GetString("V_Cat_E_Kaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Listesine Geri Dön.
        /// </summary>
        public static string V_Cat_E_ListeyeDon {
            get {
                return ResourceManager.GetString("V_Cat_E_ListeyeDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string V_Cat_I_Guncelle {
            get {
                return ResourceManager.GetString("V_Cat_I_Guncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Listesi.
        /// </summary>
        public static string V_Cat_I_h2Baslik {
            get {
                return ResourceManager.GetString("V_Cat_I_h2Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string V_Cat_I_Sil {
            get {
                return ResourceManager.GetString("V_Cat_I_Sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Kategori.
        /// </summary>
        public static string V_Cat_I_YeniKategori {
            get {
                return ResourceManager.GetString("V_Cat_I_YeniKategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string V_H_D_Aciklama {
            get {
                return ResourceManager.GetString("V_H_D_Aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir değerlendirme yazın!.
        /// </summary>
        public static string V_H_D_DegerlendirmeYazin {
            get {
                return ResourceManager.GetString("V_H_D_DegerlendirmeYazin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnceleme.
        /// </summary>
        public static string V_H_D_Inceleme {
            get {
                return ResourceManager.GetString("V_H_D_Inceleme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Metodları.
        /// </summary>
        public static string V_H_D_OdemeMetodlari {
            get {
                return ResourceManager.GetString("V_H_D_OdemeMetodlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ülkemizde gerçekleştirdiği büyük reklam kampanyası ile bilinirliğini artıran Oppo&apos;nun yeni modellerinden Oppo Reno2 Z modelinin incelemesi ile karşınızdayız. Fiyat segmentindeki rakipleri ile kıyaslandığında oldukça….
        /// </summary>
        public static string V_H_D_p_Aciklama {
            get {
                return ResourceManager.GetString("V_H_D_p_Aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ülkemizde gerçekleştirdiği büyük reklam kampanyası ile bilinirliğini artıran Oppo&apos;nun yeni modellerinden Oppo Reno2 Z modelinin incelemesi ile karşınızdayız. Fiyat segmentindeki rakipleri ile kıyaslandığında oldukça….
        /// </summary>
        public static string V_H_D_p_Inceleme {
            get {
                return ResourceManager.GetString("V_H_D_p_Inceleme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi kartına 12 taksit. Kapıda ödeme..
        /// </summary>
        public static string V_H_D_p_OdemeMetod {
            get {
                return ResourceManager.GetString("V_H_D_p_OdemeMetod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sepete Ekle.
        /// </summary>
        public static string V_H_D_SepeteEkle {
            get {
                return ResourceManager.GetString("V_H_D_SepeteEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stokta.
        /// </summary>
        public static string V_H_D_Stokta {
            get {
                return ResourceManager.GetString("V_H_D_Stokta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stokta Yok.
        /// </summary>
        public static string V_H_D_StoktaYok {
            get {
                return ResourceManager.GetString("V_H_D_StoktaYok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Kategoriler.
        /// </summary>
        public static string V_H_G_TumKategoriler {
            get {
                return ResourceManager.GetString("V_H_G_TumKategoriler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşgeldiniz!.
        /// </summary>
        public static string V_H_I_h1Baslik {
            get {
                return ResourceManager.GetString("V_H_I_h1Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teknolojide sınır tanımıyoruz!.
        /// </summary>
        public static string V_H_I_p1 {
            get {
                return ResourceManager.GetString("V_H_I_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masaüstü bilgisayar, dizüstü bilgisayar, cep telefonu, televizyon, tablet, fotoğraf makinesi ve binlerce teknoloji ürünü Vatan Bilgisayar&apos;da..
        /// </summary>
        public static string V_H_I_p2 {
            get {
                return ResourceManager.GetString("V_H_I_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adet.
        /// </summary>
        public static string V_H_L_adet {
            get {
                return ResourceManager.GetString("V_H_L_adet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu Kategoride bir ürün bulunamadı..
        /// </summary>
        public static string V_H_L_Bulunamadi {
            get {
                return ResourceManager.GetString("V_H_L_Bulunamadi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ürün bulundu..
        /// </summary>
        public static string V_H_L_urun_bulundu {
            get {
                return ResourceManager.GetString("V_H_L_urun bulundu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dilinizi Seçiniz.
        /// </summary>
        public static string V_L_I_DiliniziSeciniz {
            get {
                return ResourceManager.GetString("V_L_I_DiliniziSeciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string V_O_D_adres {
            get {
                return ResourceManager.GetString("V_O_D_adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat.
        /// </summary>
        public static string V_O_D_Fiyat {
            get {
                return ResourceManager.GetString("V_O_D_Fiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string V_O_D_Guncelle {
            get {
                return ResourceManager.GetString("V_O_D_Guncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Detay Bilgileri.
        /// </summary>
        public static string V_O_D_h2Baslik {
            get {
                return ResourceManager.GetString("V_O_D_h2Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        public static string V_O_D_KullaniciAdi {
            get {
                return ResourceManager.GetString("V_O_D_KullaniciAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miktar.
        /// </summary>
        public static string V_O_D_Miktar {
            get {
                return ResourceManager.GetString("V_O_D_Miktar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim.
        /// </summary>
        public static string V_O_D_Resim {
            get {
                return ResourceManager.GetString("V_O_D_Resim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Id.
        /// </summary>
        public static string V_O_D_SiparisId {
            get {
                return ResourceManager.GetString("V_O_D_SiparisId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Numarası.
        /// </summary>
        public static string V_O_D_SiparisNo {
            get {
                return ResourceManager.GetString("V_O_D_SiparisNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Tarihi.
        /// </summary>
        public static string V_O_D_SiparisTarihi {
            get {
                return ResourceManager.GetString("V_O_D_SiparisTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutar.
        /// </summary>
        public static string V_O_D_Tutar {
            get {
                return ResourceManager.GetString("V_O_D_Tutar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Adı.
        /// </summary>
        public static string V_O_D_UrunAdi {
            get {
                return ResourceManager.GetString("V_O_D_UrunAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Detay.
        /// </summary>
        public static string V_O_D_UrunDetay {
            get {
                return ResourceManager.GetString("V_O_D_UrunDetay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Durumu.
        /// </summary>
        public static string V_O_D_UrunDurumu {
            get {
                return ResourceManager.GetString("V_O_D_UrunDurumu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Durumunu Seçin.
        /// </summary>
        public static string V_O_D_UrunDurumuSecin {
            get {
                return ResourceManager.GetString("V_O_D_UrunDurumuSecin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünler.
        /// </summary>
        public static string V_O_D_Urunler {
            get {
                return ResourceManager.GetString("V_O_D_Urunler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaylar.
        /// </summary>
        public static string V_O_I_Detaylar {
            get {
                return ResourceManager.GetString("V_O_I_Detaylar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siparişler.
        /// </summary>
        public static string V_O_I_h2Baslik {
            get {
                return ResourceManager.GetString("V_O_I_h2Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string V_O_I_id {
            get {
                return ResourceManager.GetString("V_O_I_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Durumu.
        /// </summary>
        public static string V_O_I_SiparisDurumu {
            get {
                return ResourceManager.GetString("V_O_I_SiparisDurumu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Numarası.
        /// </summary>
        public static string V_O_I_SiparisNo {
            get {
                return ResourceManager.GetString("V_O_I_SiparisNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipariş Tarihi.
        /// </summary>
        public static string V_O_I_SiparisTarihi {
            get {
                return ResourceManager.GetString("V_O_I_SiparisTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutar.
        /// </summary>
        public static string V_O_I_Tutar {
            get {
                return ResourceManager.GetString("V_O_I_Tutar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Stok.
        /// </summary>
        public static string V_O_I_UrunStok {
            get {
                return ResourceManager.GetString("V_O_I_UrunStok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Ürün.
        /// </summary>
        public static string V_P_C_h2Baslik {
            get {
                return ResourceManager.GetString("V_P_C_h2Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alışveriş Listesine Geri Dön.
        /// </summary>
        public static string V_P_C_ListeyeDon {
            get {
                return ResourceManager.GetString("V_P_C_ListeyeDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu ürünü silmek istediğinizden emin misiniz?.
        /// </summary>
        public static string V_P_Del_h2Baslik {
            get {
                return ResourceManager.GetString("V_P_Del_h2Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Listesine Geri Dön.
        /// </summary>
        public static string V_P_Del_ListeyeDon {
            get {
                return ResourceManager.GetString("V_P_Del_ListeyeDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string V_P_Del_Sil {
            get {
                return ResourceManager.GetString("V_P_Del_Sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        public static string V_P_Det_Duzenle {
            get {
                return ResourceManager.GetString("V_P_Det_Duzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaylar.
        /// </summary>
        public static string V_P_Det_h2Baslik {
            get {
                return ResourceManager.GetString("V_P_Det_h2Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün.
        /// </summary>
        public static string V_P_Det_h4Baslik {
            get {
                return ResourceManager.GetString("V_P_Det_h4Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listeye geri dön.
        /// </summary>
        public static string V_P_Det_ListeyeDon {
            get {
                return ResourceManager.GetString("V_P_Det_ListeyeDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Güncelle.
        /// </summary>
        public static string V_P_E_h2Baslik {
            get {
                return ResourceManager.GetString("V_P_E_h2Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string V_P_E_Kaydet {
            get {
                return ResourceManager.GetString("V_P_E_Kaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Listesine Geri Dön.
        /// </summary>
        public static string V_P_E_ListeyeDon {
            get {
                return ResourceManager.GetString("V_P_E_ListeyeDon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evet.
        /// </summary>
        public static string V_P_I_Evet {
            get {
                return ResourceManager.GetString("V_P_I_Evet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string V_P_I_Guncelle {
            get {
                return ResourceManager.GetString("V_P_I_Guncelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünler.
        /// </summary>
        public static string V_P_I_h2Baslik {
            get {
                return ResourceManager.GetString("V_P_I_h2Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayır.
        /// </summary>
        public static string V_P_I_Hayir {
            get {
                return ResourceManager.GetString("V_P_I_Hayir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayır.
        /// </summary>
        public static string V_P_I_Hayir2 {
            get {
                return ResourceManager.GetString("V_P_I_Hayir2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string V_P_I_Sil {
            get {
                return ResourceManager.GetString("V_P_I_Sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Ürün.
        /// </summary>
        public static string V_P_I_YeniUrun {
            get {
                return ResourceManager.GetString("V_P_I_YeniUrun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string V_S_AL_AnaSayfa {
            get {
                return ResourceManager.GetString("V_S_AL_AnaSayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama.
        /// </summary>
        public static string V_S_AL_Arama {
            get {
                return ResourceManager.GetString("V_S_AL_Arama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori.
        /// </summary>
        public static string V_S_AL_Kategori {
            get {
                return ResourceManager.GetString("V_S_AL_Kategori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama.
        /// </summary>
        public static string V_S_AL_pc_Arama {
            get {
                return ResourceManager.GetString("V_S_AL_pc_Arama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siparişler.
        /// </summary>
        public static string V_S_AL_Siparisler {
            get {
                return ResourceManager.GetString("V_S_AL_Siparisler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün.
        /// </summary>
        public static string V_S_AL_Urun {
            get {
                return ResourceManager.GetString("V_S_AL_Urun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetim Paneli.
        /// </summary>
        public static string V_S_AL_YonetimPaneli {
            get {
                return ResourceManager.GetString("V_S_AL_YonetimPaneli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string V_S_L_AnaSayfa {
            get {
                return ResourceManager.GetString("V_S_L_AnaSayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Seçenekleri.
        /// </summary>
        public static string V_S_L_Dil {
            get {
                return ResourceManager.GetString("V_S_L_Dil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünler.
        /// </summary>
        public static string V_S_L_Urunler {
            get {
                return ResourceManager.GetString("V_S_L_Urunler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetim Paneli.
        /// </summary>
        public static string V_S_L_YonetimPaneli {
            get {
                return ResourceManager.GetString("V_S_L_YonetimPaneli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış.
        /// </summary>
        public static string V_S_LP_Cikis {
            get {
                return ResourceManager.GetString("V_S_LP_Cikis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string V_S_LP_Giris {
            get {
                return ResourceManager.GetString("V_S_LP_Giris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Ol.
        /// </summary>
        public static string V_S_LP_UyeOl {
            get {
                return ResourceManager.GetString("V_S_LP_UyeOl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünü İncele.
        /// </summary>
        public static string V_S_P_UrunuIncele {
            get {
                return ResourceManager.GetString("V_S_P_UrunuIncele", resourceCulture);
            }
        }
    }
}
